version: "3.8"
services:
  findatarxtractorparser:
    build: .
    container_name: FinDataExtractorParser
    command: gunicorn -w 4 -b 0.0.0.0:5000 FinDataExtractorParser.parser:app
    ports:
      - '5000:5000'

