[Parser]
method = pytesseract/Images

[AI]
method = Ollama/Vision

# Parser methods: pdfPlumber pyTesseract linuxTest pytesseract/Images

# AI methods: gpt llama Ollama Ollama/Schema Ollama/Vision
    # gpt: AI gives output, doesn't make JSON file
    # llama: old and slow! don't use